clear; clc;
init
%%
runID = "R0009";

% Example: load PIVLab-exported u, v
% Replace this path with your actual file
% load(fullfile(cfg.WORK_DIR, char(runID), 'pivlab_short.mat'), 'u', 'v');
load('/Users/koshiba/Dropbox/git_ignored/psp-singleport-regime/work/R0009/pivlab_proj/pivlab_proj_long/PIVlab.mat',...
    'u_filtered', 'v_filtered');
u = u_filtered; v = v_filtered;

outFile = fullfile(cfg.RESULTS_FIG_DIR, sprintf('%s_preview.mp4', runID));
%%
make_piv_quiver_movie(u, v, outFile, ...
    'Lx_m', 3.0, ...
    'Ly_m', 2.0, ...
    'dt_s', 1/6, ...
    'frame_step', 5, ...
    'quiver_step', 3, ...
    'video_fps', 10, ...
    'fig_pos', [100 100 720 480], ...
    'autoscale', 1.5, ...
    'title_prefix', sprintf('%s PIV preview', runID));